version: '3'

services:
  mailer-pg:
    image: bitnami/postgresql
    ports:
      - 5432
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=test
      - POSTGRESQL_PASSWORD=test
      - POSTGRESQL_DATABASE=test
