name: CI - Merge and Release

on:
  push: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME }}
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Create .env file
        run: |
          echo "POSTGRESQL_USERNAME=${{ secrets.POSTGRESQL_USERNAME }}" >> .env
          echo "POSTGRESQL_PASSWORD=${{ secrets.POSTGRESQL_PASSWORD }}" >> .env
          echo "POSTGRESQL_DATABASE=${{ secrets.POSTGRESQL_DATABASE }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "MAIL_LOGIN=${{ secrets.MAIL_LOGIN }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
      - name: Install Dependencies
        run: npm install


      - name: Fixing non-standard Scripts
        run: npm run lint

      - name: Run coverall Tests
        run: npm run test:coveralls
        
      - name: "Coveralls"
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}