name: CI - Release

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/changelog
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/git
          branches: main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
